version: "3.3"

# architecture: https://i.cmyui.xyz/vnImBXhZMTHF.png

services:
  ## shared/managed services

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lol123
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379

  nginx:
    image: nginx:1.19
    volumes:
    - ./nginx-templates:/etc/nginx/templates
    ports:
    - "80:80"

  ## application services

  user-gateway-service:
    image: user-gateway-service:latest
    ports:
      - 10000:80
    environment:
      # asgi + app
      - APP_ENV=local
      - APP_COMPONENT=api
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - LOG_LEVEL=20
    volumes:
      - ./repos/user-gateway-service/mount:/srv/root
      - ./repos/user-gateway-service/scripts:/scripts

  users-service:
    image: users-service:latest
    ports:
      - 11000:80
    environment:
      # asgi + app
      - APP_ENV=local
      - APP_COMPONENT=api
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - LOG_LEVEL=20
      # database
      - READ_DB_DRIVER=mysql
      - READ_DB_USER=root
      - READ_DB_PASS=lol123
      - READ_DB_HOST=mysql
      - READ_DB_PORT=3306
      - READ_DB_NAME=users_dev
      - WRITE_DB_DRIVER=mysql
      - WRITE_DB_USER=root
      - WRITE_DB_PASS=lol123
      - WRITE_DB_HOST=mysql
      - WRITE_DB_PORT=3306
      - WRITE_DB_NAME=users_dev
      - MIN_DB_POOL_SIZE=5
      - MAX_DB_POOL_SIZE=10
      - DB_USE_SSL=false
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # rabbitmq
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASS=guest
      # misc
      - AUTH_SESSION_DURATION=3600
    volumes:
      - ./repos/users-service/mount:/srv/root
      - ./repos/users-service/scripts:/scripts
    depends_on:
      - mysql
      - redis
      # - rabbitmq

  bancho-service:
    image: bancho-service:latest
    ports:
      - 12000:80
    environment:
      # asgi + app
      - APP_ENV=local
      - APP_COMPONENT=api
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - LOG_LEVEL=20
      # database
      - READ_DB_DRIVER=mysql
      - READ_DB_USER=root
      - READ_DB_PASS=lol123
      - READ_DB_HOST=mysql
      - READ_DB_PORT=3306
      - READ_DB_NAME=bancho_dev
      - WRITE_DB_DRIVER=mysql
      - WRITE_DB_USER=root
      - WRITE_DB_PASS=lol123
      - WRITE_DB_HOST=mysql
      - WRITE_DB_PORT=3306
      - WRITE_DB_NAME=bancho_dev
      - MIN_DB_POOL_SIZE=5
      - MAX_DB_POOL_SIZE=10
      - DB_USE_SSL=false
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # rabbitmq
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASS=guest
    volumes:
      - ./repos/bancho-service/mount:/srv/root
      - ./repos/bancho-service/scripts:/scripts
    depends_on:
      - mysql
      # - redis
      # - rabbitmq

  chat-service:
    image: chat-service:latest
    ports:
      - 15000:80
    environment:
      # asgi + app
      - APP_ENV=local
      - APP_COMPONENT=api
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - LOG_LEVEL=10
      # database
      - READ_DB_DRIVER=mysql
      - READ_DB_USER=root
      - READ_DB_PASS=lol123
      - READ_DB_HOST=mysql
      - READ_DB_PORT=3306
      - READ_DB_NAME=chat_dev
      - WRITE_DB_DRIVER=mysql
      - WRITE_DB_USER=root
      - WRITE_DB_PASS=lol123
      - WRITE_DB_HOST=mysql
      - WRITE_DB_PORT=3306
      - WRITE_DB_NAME=chat_dev
      - MIN_DB_POOL_SIZE=5
      - MAX_DB_POOL_SIZE=10
      - DB_USE_SSL=false
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # rabbitmq
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASS=guest
    volumes:
      - ./repos/chat-service/mount:/srv/root
      - ./repos/chat-service/scripts:/scripts
    depends_on:
      - mysql
      - redis
      # - rabbitmq

  # beatmaps-service:
  #   image: beatmaps-service:latest
  #   ports:
  #     - 13000:80
  #   environment:
  #     # asgi + app
  #     - APP_ENV=local
  #     - APP_COMPONENT=api
  #     - APP_HOST=0.0.0.0
  #     - APP_PORT=80
  #     - LOG_LEVEL=20
  #     # database
  #     - READ_DB_DRIVER=mysql
  #     - READ_DB_USER=root
  #     - READ_DB_PASS=lol123
  #     - READ_DB_HOST=mysql
  #     - READ_DB_PORT=3306
  #     - READ_DB_NAME=beatmaps_dev
  #     - WRITE_DB_DRIVER=mysql
  #     - WRITE_DB_USER=root
  #     - WRITE_DB_PASS=lol123
  #     - WRITE_DB_HOST=mysql
  #     - WRITE_DB_PORT=3306
  #     - WRITE_DB_NAME=beatmaps_dev
  #     - MIN_DB_POOL_SIZE=5
  #     - MAX_DB_POOL_SIZE=10
  #     - DB_USE_SSL=false
  #     # redis
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     # rabbitmq
  #     - AMQP_HOST=rabbitmq
  #     - AMQP_PORT=5672
  #     - AMQP_USER=guest
  #     - AMQP_PASS=guest
  #   volumes:
  #     - ./repos/beatmaps-service/mount:/srv/root
  #     - ./repos/beatmaps-service/scripts:/scripts
  #   depends_on:
  #     - mysql
  #     # - redis
  #     # - rabbitmq

  # clans-service:
  #   image: clans-service:latest
  #   ports:
  #     - 14000:80
  #   environment:
  #     # asgi + app
  #     - APP_ENV=local
  #     - APP_COMPONENT=api
  #     - APP_HOST=0.0.0.0
  #     - APP_PORT=80
  #     - LOG_LEVEL=20
  #     # database
  #     - READ_DB_DRIVER=mysql
  #     - READ_DB_USER=root
  #     - READ_DB_PASS=lol123
  #     - READ_DB_HOST=mysql
  #     - READ_DB_PORT=3306
  #     - READ_DB_NAME=clans_dev
  #     - WRITE_DB_DRIVER=mysql
  #     - WRITE_DB_USER=root
  #     - WRITE_DB_PASS=lol123
  #     - WRITE_DB_HOST=mysql
  #     - WRITE_DB_PORT=3306
  #     - WRITE_DB_NAME=clans_dev
  #     - MIN_DB_POOL_SIZE=5
  #     - MAX_DB_POOL_SIZE=10
  #     - DB_USE_SSL=false
  #     # redis
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     # rabbitmq
  #     - AMQP_HOST=rabbitmq
  #     - AMQP_PORT=5672
  #     - AMQP_USER=guest
  #     - AMQP_PASS=guest
  #   volumes:
  #     - ./repos/clans-service/mount:/srv/root
  #     - ./repos/clans-service/scripts:/scripts
  #   depends_on:
  #     - mysql
  #     # - redis
  #     # - rabbitmq
